<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PengaduanSeeder extends Seeder
{
    public function run()
    {
        $pengaduanData = [
            [
                'nomor_pengaduan' => 'PND001',
                'pelapor' => 'John Doe',
                'kondisi_masalah' => '1 Line',
                'lokasi' => 'Jalan Sudirman',
                'tanggal_pengaduan' => '2024-12-01',
                'jam_aduan' => '08:00:00',
                'keterangan_masalah' => '1 Line tidak menyala',
                'uraian_masalah' => 'Lampu mati total sejak 3 hari lalu',
                'tanggal_penyelesaian' => '2024-12-02',
                'jam_penyelesaian' => '12:00:00',
                'durasi_penyelesaian' => '240',
                'penyelesaian_masalah' => 'Lampu diganti',
                'pencegahan_masalah' => 'Periksa kabel secara berkala',
                'pengelompokan_masalah' => 'Internal',
                'status' => 'Selesai',
            ],
            [
                'nomor_pengaduan' => 'PND002',
                'pelapor' => 'Jane Smith',
                'kondisi_masalah' => 'Tiang',
                'lokasi' => 'Jalan Thamrin',
                'tanggal_pengaduan' => '2024-12-02',
                'jam_aduan' => '10:30:00',
                'keterangan_masalah' => 'Tiang miring',
                'uraian_masalah' => 'Tiang hampir roboh akibat angin',
                'tanggal_penyelesaian' => null,
                'jam_penyelesaian' => null,
                'durasi_penyelesaian' => null,
                'penyelesaian_masalah' => null,
                'pencegahan_masalah' => 'Perkuat struktur tiang',
                'pengelompokan_masalah' => 'Eksternal',
                'status' => 'Pending',
            ],
            [
                'nomor_pengaduan' => 'PND003',
                'pelapor' => 'Ali Hasan',
                'kondisi_masalah' => 'Panel',
                'lokasi' => 'Komplek Perumahan A',
                'tanggal_pengaduan' => '2024-12-03',
                'jam_aduan' => '13:15:00',
                'keterangan_masalah' => 'Panel konslet',
                'uraian_masalah' => 'Panel tidak berfungsi akibat korsleting',
                'tanggal_penyelesaian' => '2024-12-04',
                'jam_penyelesaian' => '16:00:00',
                'durasi_penyelesaian' => '285',
                'penyelesaian_masalah' => 'Panel diperbaiki',
                'pencegahan_masalah' => 'Lakukan pemeriksaan setiap bulan',
                'pengelompokan_masalah' => 'Internal',
                'status' => 'Selesai',
            ],
            [
                'nomor_pengaduan' => 'PND004',
                'pelapor' => 'Maria Ulfa',
                'kondisi_masalah' => '1 Line',
                'lokasi' => 'Jalan Ahmad Yani',
                'tanggal_pengaduan' => '2024-12-04',
                'jam_aduan' => '09:45:00',
                'keterangan_masalah' => 'Lampu redup',
                'uraian_masalah' => 'Lampu 1 Line tidak menyala terang',
                'tanggal_penyelesaian' => null,
                'jam_penyelesaian' => null,
                'durasi_penyelesaian' => null,
                'penyelesaian_masalah' => null,
                'pencegahan_masalah' => 'Ganti dengan lampu LED',
                'pengelompokan_masalah' => 'Internal',
                'status' => 'Proses',
            ],
            [
                'nomor_pengaduan' => 'PND005',
                'pelapor' => 'Rina Kartika',
                'kondisi_masalah' => 'Tiang',
                'lokasi' => 'Jalan MT Haryono',
                'tanggal_pengaduan' => '2024-12-05',
                'jam_aduan' => '07:00:00',
                'keterangan_masalah' => 'Tiang patah',
                'uraian_masalah' => 'Tiang patah akibat kecelakaan',
                'tanggal_penyelesaian' => '2024-12-07',
                'jam_penyelesaian' => '11:00:00',
                'durasi_penyelesaian' => '290',
                'penyelesaian_masalah' => 'Tiang diganti baru',
                'pencegahan_masalah' => 'Periksa kondisi tiang setelah hujan',
                'pengelompokan_masalah' => 'Eksternal',
                'status' => 'Selesai',
            ],
            [
                'nomor_pengaduan' => 'PND006',
                'pelapor' => 'Fauzan Zaki',
                'kondisi_masalah' => 'Panel',
                'lokasi' => 'Komplek Perumahan B',
                'tanggal_pengaduan' => '2024-12-05',
                'jam_aduan' => '15:30:00',
                'keterangan_masalah' => 'Panel terbakar',
                'uraian_masalah' => 'Panel rusak akibat korsleting parah',
                'tanggal_penyelesaian' => null,
                'jam_penyelesaian' => null,
                'durasi_penyelesaian' => null,
                'penyelesaian_masalah' => null,
                'pencegahan_masalah' => 'Pastikan kabel tidak longgar',
                'pengelompokan_masalah' => 'Internal',
                'status' => 'Proses',
            ],
            [
                'nomor_pengaduan' => 'PND007',
                'pelapor' => 'Nina Sari',
                'kondisi_masalah' => '1 Line',
                'lokasi' => 'Jalan KH Ahmad Dahlan',
                'tanggal_pengaduan' => '2024-12-06',
                'jam_aduan' => '17:00:00',
                'keterangan_masalah' => 'Lampu mati sebagian',
                'uraian_masalah' => 'Hanya sebagian lampu yang menyala',
                'tanggal_penyelesaian' => null,
                'jam_penyelesaian' => null,
                'durasi_penyelesaian' => null,
                'penyelesaian_masalah' => null,
                'pencegahan_masalah' => 'Periksa koneksi kabel utama',
                'pengelompokan_masalah' => 'Internal',
                'status' => 'Pending',
            ],
            [
                'nomor_pengaduan' => 'PND008',
                'pelapor' => 'Yusuf Ali',
                'kondisi_masalah' => 'Tiang',
                'lokasi' => 'Jalan Kartini',
                'tanggal_pengaduan' => '2024-12-06',
                'jam_aduan' => '20:30:00',
                'keterangan_masalah' => 'Tiang goyah',
                'uraian_masalah' => 'Tiang bergoyang saat hujan deras',
                'tanggal_penyelesaian' => null,
                'jam_penyelesaian' => null,
                'durasi_penyelesaian' => null,
                'penyelesaian_masalah' => null,
                'pencegahan_masalah' => 'Tambahkan penyangga',
                'pengelompokan_masalah' => 'Eksternal',
                'status' => 'Proses',
            ],
            [
                'nomor_pengaduan' => 'PND009',
                'pelapor' => 'Dewi Lestari',
                'kondisi_masalah' => '1 Line',
                'lokasi' => 'Jalan Panglima Sudirman',
                'tanggal_pengaduan' => '2024-12-07',
                'jam_aduan' => '22:00:00',
                'keterangan_masalah' => 'Lampu menyala siang hari',
                'uraian_masalah' => 'Lampu 1 Line tetap menyala meski siang',
                'tanggal_penyelesaian' => null,
                'jam_penyelesaian' => null,
                'durasi_penyelesaian' => null,
                'penyelesaian_masalah' => null,
                'pencegahan_masalah' => 'Atur ulang timer',
                'pengelompokan_masalah' => 'Internal',
                'status' => 'Pending',
            ],
            [
                'nomor_pengaduan' => 'PND010',
                'pelapor' => 'Ahmad Ridwan',
                'kondisi_masalah' => 'Panel',
                'lokasi' => 'Jalan Dewi Sartika',
                'tanggal_pengaduan' => '2024-12-08',
                'jam_aduan' => '08:30:00',
                'keterangan_masalah' => 'Panel tidak berfungsi',
                'uraian_masalah' => 'Panel mati total akibat korsleting',
                'tanggal_penyelesaian' => null,
                'jam_penyelesaian' => null,
                'durasi_penyelesaian' => null,
                'penyelesaian_masalah' => null,
                'pencegahan_masalah' => 'Gunakan panel yang lebih tahan air',
                'pengelompokan_masalah' => 'Eksternal',
                'status' => 'Proses',
            ],
        ];

        DB::table('pengaduan')->insert($pengaduanData);
    }
}